workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

Update Flake.nix:
  image: nixos/nix:latest
  script:
    - git config user.email "snowflake@caspervk.net"
    - git config user.name "snowflake"
    - nix --extra-experimental-features nix-command --extra-experimental-features flakes flake update --commit-lock-file
    - git push https://oauth2:$ACCESS_TOKEN@gitlab.com/$CI_PROJECT_PATH_SLUG
